<div class="edan-record-container">
  <div class="edan-row">
    <h2>How to Use this Collection</h2>

    <h3>Restrictions on Use</h3>
    <p><?php print $docs_edanead['Collection_Notes'][8]['content']; ?></p>

    <h3>Ownership &amp; Literary Rights</h3>
    <p><?php print $docs_edanead['Collection_Notes'][4]['content']; ?></p>

    <h3>Available Formats</h3>
    <p><?php print $docs_edanead['Collection_Notes'][12]['content']; ?></p>

    <h3>How to Cite this Collection</h3>
    <p><?php print $docs_edanead['Collection_Notes'][6]['content']; ?></p>

  </div>
</div>